//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cabshare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.TimeSpan> time1 { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public Nullable<int> MAXNO { get; set; }
        public string fbid { get; set; }
        public string psid { get; set; }
        public string names { get; set; }
    }
}
